In [4]:
conda install pytorch torchvision -c pytorch

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\DayoBanjo\Anaconda3

  added / updated specs:
    - pytorch
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.1                |           py37_0         2.8 MB
    cudatoolkit-10.0.130       |                0       250.0 MB
    ninja-1.9.0                |   py37h74a9793_0         238 KB
    pytorch-1.2.0              |py3.7_cuda100_cudnn7_1       479.3 MB  pytorch
    torchvision-0.4.0          |       py37_cu100         2.3 MB  pytorch
    ------------------------------------------------------------
                                           Total:       734.6 MB

The following NEW packages will be INSTALLED:

  cudatoolkit        pkgs/main/win-64::cudatoolkit-10.0.130-0
  ninja              pkgs/main/win-64::ninja-1.9.0-py37h74a9793_0
  pytorch            pytorch

cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0 MB  | ######     |  60% 
cudatoolkit-10.0.130 | 250.0

cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  86% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  86% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  86% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  86% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  86% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  86% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  86% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  86% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  86% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  86% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  86% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  86% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  86% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  86% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  87% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  87% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  87% 
cudatoolkit-10.0.130 | 250.0 MB  | ########6  |  87% 
cudatoolkit-10.0.130 | 250.0

pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3 MB  | 6          |   6% 
pytorch-1.2.0        | 479.3

pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3 MB  | #3         |  13% 
pytorch-1.2.0        | 479.3

pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3 MB  | ##1        |  21% 
pytorch-1.2.0        | 479.3

pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3 MB  | ##9        |  30% 
pytorch-1.2.0        | 479.3


CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/pytorch/win-64/pytorch-1.2.0-py3.7_cuda100_cudnn7_1.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.




In [2]:
import torch 

In [3]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [26]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 5 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [5]:
y = activation((weights * features).sum() + bias )

In [6]:
y 

tensor([[0.1595]])

In [7]:
y.shape 

torch.Size([1, 1])

In [12]:
z = y.resize_(2, 1)

In [13]:
z

tensor([[0.1595],
        [0.0000]])

In [14]:
z = z.resize_(1,2)

In [15]:
z

tensor([[0.1595, 0.0000]])

In [31]:
#multiply_result = activation(
k= activation(torch.mm(features, weights.view(5,1)) + bias)


In [43]:
j = activation(torch.mm(features, weights.view(5,1) +bias))

In [44]:
k = torch.randn((2,3))

In [45]:
k

tensor([[ 0.2028,  2.4505,  2.0256],
        [ 1.7792, -0.9179, -0.4578]])

In [46]:
k.view(3,2)

tensor([[ 0.2028,  2.4505],
        [ 2.0256,  1.7792],
        [-0.9179, -0.4578]])

In [48]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [57]:
features.shape,W1.shape

(torch.Size([1, 3]), torch.Size([3, 2]))

In [59]:
features, W1

(tensor([[-0.1468,  0.7861,  0.9468]]), tensor([[-1.1143,  1.6908],
         [-0.8948, -0.3556],
         [ 1.2324,  0.1382]]))

In [62]:
h= activation(torch.mm(features,W1) + B1)
output = activation(torch.mm(h, W2) + B2)

In [63]:
output

tensor([[0.3171]])

In [64]:
import numpy as np


In [66]:
a = np.random.rand(4,3)
b = torch.from_numpy(a)

In [67]:
a,b

(array([[0.67950231, 0.30632292, 0.09739535],
        [0.22201281, 0.8734003 , 0.16911713],
        [0.98181159, 0.68644502, 0.30451184],
        [0.72831073, 0.81351399, 0.24998659]]),
 tensor([[0.6795, 0.3063, 0.0974],
         [0.2220, 0.8734, 0.1691],
         [0.9818, 0.6864, 0.3045],
         [0.7283, 0.8135, 0.2500]], dtype=torch.float64))

In [69]:
b.numpy()

array([[0.67950231, 0.30632292, 0.09739535],
       [0.22201281, 0.8734003 , 0.16911713],
       [0.98181159, 0.68644502, 0.30451184],
       [0.72831073, 0.81351399, 0.24998659]])

In [70]:
b.mul_(3)

tensor([[2.0385, 0.9190, 0.2922],
        [0.6660, 2.6202, 0.5074],
        [2.9454, 2.0593, 0.9135],
        [2.1849, 2.4405, 0.7500]], dtype=torch.float64)

In [71]:
a

array([[2.03850693, 0.91896877, 0.29218605],
       [0.66603844, 2.6202009 , 0.50735138],
       [2.94543476, 2.05933507, 0.91353551],
       [2.1849322 , 2.44054197, 0.74995976]])